name:  CI Bliud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: get_avr-gcc
      run:  sudo apt-get install gcc-avr binutils-avr avr-libc
    - name: bulid
      run: make -C 3_Implementation/ run
